### ISSUE TITLE
Incompatible Xcode project

### ISSUE THREAD

**Issue by handsomegui** [cculianu/Electron-Cash#11]
Hi, as the title stated, problem found when i generate project for iOS.

env:
```
Python: 3.7 (changed from python3.5 to python3.7)
OSX: 10.11.6
Xcode: 8.2.1
```
```
Failed to load project at '/Users/zhenweigui/.code/electrum-app/electrum/ios/iOS/Electron-Cash.xcodeproj', incompatible project version.
```

Could someone tell me, Is it because of the python version i used?
Thanks in advance.

**Comment by cculianu** [comment]
HI,

I think with the latest toolkit (briefcase) you actually now need to be on OSX 10.13 (High Sierra) with the latest Xcode 9.x.  :/

I know, it sucks.  I hate upgrading too. But you sort of have to for this.  Blame Apple. :)

**Comment by handsomegui** [comment]
Oh... my old mac laptop stop at OSX 10.11.6. Can not upgrade further:(

I might need to buy a new one in the future:(

Thank you for the reply.

**Comment by cculianu** [comment]
You could always install a VMWare vm with High Sierra on it (that's what I did at first before upgrading!).

It's a bit tricky to find a vm with high sierra -- but they are available via bittorrent.

Yeah sorry.  These tools I used to generate the project are to blame really.. :/

**Comment by guizhenwei** [comment]
> You could always install a VMWare vm with High Sierra on it (that's what I did at first before upgrading!).
> 
> It's a bit tricky to find a vm with high sierra -- but they are available via bittorrent.
> 
> Yeah sorry. These tools I used to generate the project are to blame really.. :/

Cool!

Thank you for pointing out a new direction to dig. I will try it later.
