### ISSUE TITLE
Any way to delete wallet in IOS app?

### ISSUE THREAD

**Issue by tdrusk** [cculianu/Electron-Cash#4]
I've dug through the settings and don't see a way to delete a wallet. Is there a way to do this?

**Comment by cculianu** [comment]
Heh, yes.  The "Wallet drawer" dropdown has options on the right.  They only become visible after you successfully open a wallet.  You can only delete a wallet that isn't currently open (so you need at least 2 wallets to delete 1, and you can't delete the last wallet).

Maybe this screenshot will make it clearer.

<img width="444" alt="screen shot 2018-06-14 at 12 20 55 am" src="https://user-images.githubusercontent.com/266627/41378815-f1126714-6f68-11e8-928f-150791205a5b.png">

**Comment by tdrusk** [comment]
I see! So you can’t be ‘in’ a wallet to delete it. That makes perfect sense now that I think about it.

**Comment by cculianu** [comment]
Yeah.  Actually the app wants to avoid being in a "I have no wallet opened" state (even though such a state is defined and legal and is the state you're in initially if you don't enter your password correctly) -- I thought it might just be confusing to users, which is why it's disallowed.
