### ISSUE TITLE
BIP39 seed import failed for a user. Works in desktop version. Investigate why!

### ISSUE THREAD

**Issue by cculianu** [cculianu/Electron-Cash#7]
From /u/manufoy on reddit:

> Hey, the Electron Cash wallet is working really well, however, there was an issue when I tried to import a BIP39 seed with a passphrase into the Electron Cash iOS app. The seed has a derivation path of m/44'/0'/0'/0, and has a passphrase. The seed and passphrase worked just fine in the Bitcoin.com wallet and in the desktop version of Electron Cash. But no matter what I tried, the iOS version of Electron Cash consistently imported the wrong keys.

>Eventually, I managed to get the wallet working by importing the Account Extended Private Key (xprv), using the master key option.

>Is there a known issue with importing BIP39 mnemonics in the iOS version of Electron Cash?

**Comment by flysteak** [comment]
I was able to generate another seed to reproduce this issue using a different seed. The same thing happened as I previously described.

Importing the seed and passphrase in the iOS version of Electron Cash results in keys that don't match, when importing the the xprv key results in all the keys matching.

Here is the details of the seed I generated:

**Seed Extension/Passphrase:**
 TestWallet_333###

**Seed:**
dynamic
among
true
lyrics
region
foster
glimpse
squirrel
news
voyage
render
donor

**Derivation path:**
m/44'/0'/0' 

**xprv key:**
xprv9xurCxqDH8JCWcRzzoVXsc3uxbF1bbeggWjMUu28kBATq7eKy2fwVJN9QHQLJxUABXAtQr3xaAXupzVd6ekZqh2k77AUrdxB9x4zmDcyf6R

**Comment by cculianu** [comment]
Wow. It turns out I was doing something dumb in processing the user input.  I was converting it all to lowercase.  bad bad bad!

I ended up removing the lowercase call (which indeed doesn't exist in the Desktop version) and passing the Seed extension (passphrase) "as-is" along the chain.  This did it.

I also am passing the seed itself "as-is" along the chain (for Bip39 seeds -- Electron Cash seeds are always lowercase). 

So that did it.  I tested the seed you provided again and sure enough it produces the same addresses now as the desktop wallet and as that xprv key.

Sorry for that! My bad!

A new build has been released to TestFlight (build 212) which fixes this.  Please try it out and let me know if you are satisfied with it, so that I may close this issue.

**Comment by flysteak** [comment]
I just checked. I have no issue with importing seeds now. Everything works great now.

**Comment by cculianu** [comment]
Great!  Thank you my man for following up and for reporting this.  This is definitely one of the best catches as far as app correctness goes.  I'm a bit embarrassed I made this mistake, but stuff happens. :)

Thanks again!!
