### ISSUE TITLE
Layout on iPhone X - The "notch" interferes with some layouts. 

### ISSUE THREAD

**Issue by cculianu** [cculianu/Electron-Cash#8]
Suggestion: padding that side with the notch. *shakes fist at Apple*

Provided by "Devar" from slack.

> "I just realised the wallet supports orientation. Unfortunately this breaks a fair but of the UI as the infamous notch covers some of the display area. the right hand side in this case.. wait... and if i have the notch on the left hand side... interfers with the rendering. You'll have to introduce some padding the side depending on detected orientation so text/boxes are not rendered under the notch"

**Comment by Devar** [comment]
Particularly an issue on the following screens:
* Wallets main screen
* Transaction Details
* Address Details
* Coin Info
* Address Converter
* Network settings

**Comment by cculianu** [comment]
Ok, I think I fixed this.  I'll push out a build soon and when I do I'll let you know and if it looks fine, we can close this issue.  Thanks again for reporting this!

**Comment by Devar** [comment]
Tested all these screens in all orientations and overlap with notch is now fixed.

**Comment by cculianu** [comment]
Dude you're a rockstar.  Thanks again for all the great insights thus far.  

Ok, closing the issue.
